---

root: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

env:
  browser: true
  node: true
  jest: true

parserOptions:
  ecmaVersion: 2020

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
  no-console: 0
  import/extensions: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
      - req
      - reply